{{- if $.Values.db.enabled }}

{{- $apiSecretName := "db-dcim-api" }}
{{- $apiExisting := lookup "v1" "Secret" $.Release.Namespace $apiSecretName }}
{{- $apiPassword := "" }}
{{- if $apiExisting }}
{{- $apiPassword = index $apiExisting.data "password" | b64dec }}
{{- else }}
{{- $apiPassword = randAlphaNum 32 }}
{{- end }}

{{- $operatorSecretName := "db-dcim-operator" }}
{{- $operatorExisting := lookup "v1" "Secret" $.Release.Namespace $operatorSecretName }}
{{- $operatorPassword := "" }}
{{- if $operatorExisting }}
{{- $operatorPassword = index $operatorExisting.data "password" | b64dec }}
{{- else }}
{{- $operatorPassword = randAlphaNum 32 }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $apiSecretName }}
  labels:
    {{- include "dcim.labels" (dict "root" $ "name" "db" "component" "database") | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: dcim_api
  password: {{ $apiPassword | quote }}
  uri: postgresql://dcim_api:{{ $apiPassword }}@{{ include "dcim.db.host" . }}:5432/dcim

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $operatorSecretName }}
  labels:
    {{- include "dcim.labels" (dict "root" $ "name" "db" "component" "database") | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: dcim_operator
  password: {{ $operatorPassword | quote }}
  uri: postgresql://dcim_operator:{{ $operatorPassword }}@{{ include "dcim.db.host" . }}:5432/dcim

{{- end }}
