root = "/src"
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/api ./api/cmd/api"
entrypoint = "tmp/api"
include_ext = ["go", "mod", "sum"]
include_dir = ["api"]
exclude_dir = ["tmp"]
delay = 500

[log]
time = false
