// Code generated by _generate-dbconstraints. DO NOT EDIT.

package dbconst

const (
	// ConstraintAssetEventsCkEventType is defined on core.asset_events.
	ConstraintAssetEventsCkEventType = "asset_events_ck_event_type"
	// ConstraintAssetEventsFkAsset is defined on core.asset_events.
	ConstraintAssetEventsFkAsset = "asset_events_fk_asset"
	// ConstraintAssetsCkStatus is defined on core.assets.
	ConstraintAssetsCkStatus = "assets_ck_status"
	// ConstraintAssetsFkDeviceCatalog is defined on core.assets.
	ConstraintAssetsFkDeviceCatalog = "assets_fk_device_catalog"
	// ConstraintAssetsUqAssetTag is defined on core.assets.
	ConstraintAssetsUqAssetTag = "assets_uq_asset_tag"
	// ConstraintAssetsUqSerialNumber is defined on core.assets.
	ConstraintAssetsUqSerialNumber = "assets_uq_serial_number"
	// ConstraintDeviceCatalogsCkCategory is defined on core.device_catalogs.
	ConstraintDeviceCatalogsCkCategory = "device_catalogs_ck_category"
	// ConstraintDeviceCatalogsUqManufacturerModel is defined on core.device_catalogs.
	ConstraintDeviceCatalogsUqManufacturerModel = "device_catalogs_uq_manufacturer_model"
	// ConstraintLogicalConnectionsCkConnectionType is defined on core.logical_connections.
	ConstraintLogicalConnectionsCkConnectionType = "logical_connections_ck_connection_type"
	// ConstraintLogicalConnectionsFkADevice is defined on core.logical_connections.
	ConstraintLogicalConnectionsFkADevice = "logical_connections_fk_a_device"
	// ConstraintLogicalConnectionsFkBDevice is defined on core.logical_connections.
	ConstraintLogicalConnectionsFkBDevice = "logical_connections_fk_b_device"
	// ConstraintLogicalConnectionsFkDesign is defined on core.logical_connections.
	ConstraintLogicalConnectionsFkDesign = "logical_connections_fk_design"
	// ConstraintLogicalDesignsCkStatus is defined on core.logical_designs.
	ConstraintLogicalDesignsCkStatus = "logical_designs_ck_status"
	// ConstraintLogicalDesignsUqName is defined on core.logical_designs.
	ConstraintLogicalDesignsUqName = "logical_designs_uq_name"
	// ConstraintLogicalDeviceLayoutsFkDevice is defined on core.logical_device_layouts.
	ConstraintLogicalDeviceLayoutsFkDevice = "logical_device_layouts_fk_device"
	// ConstraintLogicalDeviceLayoutsUqDevice is defined on core.logical_device_layouts.
	ConstraintLogicalDeviceLayoutsUqDevice = "logical_device_layouts_uq_device"
	// ConstraintLogicalDevicesCkRole is defined on core.logical_devices.
	ConstraintLogicalDevicesCkRole = "logical_devices_ck_role"
	// ConstraintLogicalDevicesFkCatalog is defined on core.logical_devices.
	ConstraintLogicalDevicesFkCatalog = "logical_devices_fk_catalog"
	// ConstraintLogicalDevicesFkDesign is defined on core.logical_devices.
	ConstraintLogicalDevicesFkDesign = "logical_devices_fk_design"
	// ConstraintLogicalDevicesUqDesignLabel is defined on core.logical_devices.
	ConstraintLogicalDevicesUqDesignLabel = "logical_devices_uq_design_label"
	// ConstraintNotesCkSingleRef is defined on core.notes.
	ConstraintNotesCkSingleRef = "notes_ck_single_ref"
	// ConstraintNotesFkAsset is defined on core.notes.
	ConstraintNotesFkAsset = "notes_fk_asset"
	// ConstraintNotesFkDeviceCatalog is defined on core.notes.
	ConstraintNotesFkDeviceCatalog = "notes_fk_device_catalog"
	// ConstraintNotesFkLogicalConnection is defined on core.notes.
	ConstraintNotesFkLogicalConnection = "notes_fk_logical_connection"
	// ConstraintNotesFkLogicalDesign is defined on core.notes.
	ConstraintNotesFkLogicalDesign = "notes_fk_logical_design"
	// ConstraintNotesFkLogicalDevice is defined on core.notes.
	ConstraintNotesFkLogicalDevice = "notes_fk_logical_device"
	// ConstraintNotesFkPhysicalConnection is defined on core.notes.
	ConstraintNotesFkPhysicalConnection = "notes_fk_physical_connection"
	// ConstraintNotesFkPlacement is defined on core.notes.
	ConstraintNotesFkPlacement = "notes_fk_placement"
	// ConstraintNotesFkPortDefinition is defined on core.notes.
	ConstraintNotesFkPortDefinition = "notes_fk_port_definition"
	// ConstraintNotesFkRack is defined on core.notes.
	ConstraintNotesFkRack = "notes_fk_rack"
	// ConstraintNotesFkRackRow is defined on core.notes.
	ConstraintNotesFkRackRow = "notes_fk_rack_row"
	// ConstraintNotesFkRoom is defined on core.notes.
	ConstraintNotesFkRoom = "notes_fk_room"
	// ConstraintNotesFkSite is defined on core.notes.
	ConstraintNotesFkSite = "notes_fk_site"
	// ConstraintPhysicalConnectionsFkAPlacement is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkAPlacement = "physical_connections_fk_a_placement"
	// ConstraintPhysicalConnectionsFkAPort is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkAPort = "physical_connections_fk_a_port"
	// ConstraintPhysicalConnectionsFkBPlacement is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkBPlacement = "physical_connections_fk_b_placement"
	// ConstraintPhysicalConnectionsFkBPort is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkBPort = "physical_connections_fk_b_port"
	// ConstraintPhysicalConnectionsFkCableAsset is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkCableAsset = "physical_connections_fk_cable_asset"
	// ConstraintPhysicalConnectionsFkLogicalConnection is defined on core.physical_connections.
	ConstraintPhysicalConnectionsFkLogicalConnection = "physical_connections_fk_logical_connection"
	// ConstraintPhysicalConnectionsUqEndpoints is defined on core.physical_connections.
	ConstraintPhysicalConnectionsUqEndpoints = "physical_connections_uq_endpoints"
	// ConstraintPlacementsCkExclusiveArc is defined on core.placements.
	ConstraintPlacementsCkExclusiveArc = "placements_ck_exclusive_arc"
	// ConstraintPlacementsCkSlotType is defined on core.placements.
	ConstraintPlacementsCkSlotType = "placements_ck_slot_type"
	// ConstraintPlacementsCkUnitStart is defined on core.placements.
	ConstraintPlacementsCkUnitStart = "placements_ck_unit_start"
	// ConstraintPlacementsFkAsset is defined on core.placements.
	ConstraintPlacementsFkAsset = "placements_fk_asset"
	// ConstraintPlacementsFkLogicalDevice is defined on core.placements.
	ConstraintPlacementsFkLogicalDevice = "placements_fk_logical_device"
	// ConstraintPlacementsFkParent is defined on core.placements.
	ConstraintPlacementsFkParent = "placements_fk_parent"
	// ConstraintPlacementsFkPortDefinition is defined on core.placements.
	ConstraintPlacementsFkPortDefinition = "placements_fk_port_definition"
	// ConstraintPlacementsFkRack is defined on core.placements.
	ConstraintPlacementsFkRack = "placements_fk_rack"
	// ConstraintPortCompatibilitiesCkCompatibleCategory is defined on core.port_compatibilities.
	ConstraintPortCompatibilitiesCkCompatibleCategory = "port_compatibilities_ck_compatible_category"
	// ConstraintPortCompatibilitiesFkCatalog is defined on core.port_compatibilities.
	ConstraintPortCompatibilitiesFkCatalog = "port_compatibilities_fk_catalog"
	// ConstraintPortCompatibilitiesFkPortDefinition is defined on core.port_compatibilities.
	ConstraintPortCompatibilitiesFkPortDefinition = "port_compatibilities_fk_port_definition"
	// ConstraintPortCompatibilitiesUqPortCategoryCatalog is defined on core.port_compatibilities.
	ConstraintPortCompatibilitiesUqPortCategoryCatalog = "port_compatibilities_uq_port_category_catalog"
	// ConstraintPortDefinitionsCkDirection is defined on core.port_definitions.
	ConstraintPortDefinitionsCkDirection = "port_definitions_ck_direction"
	// ConstraintPortDefinitionsCkPortType is defined on core.port_definitions.
	ConstraintPortDefinitionsCkPortType = "port_definitions_ck_port_type"
	// ConstraintPortDefinitionsFkDeviceCatalog is defined on core.port_definitions.
	ConstraintPortDefinitionsFkDeviceCatalog = "port_definitions_fk_device_catalog"
	// ConstraintPortDefinitionsUqCatalogName is defined on core.port_definitions.
	ConstraintPortDefinitionsUqCatalogName = "port_definitions_uq_catalog_name"
	// ConstraintRackRowsFkRoom is defined on core.rack_rows.
	ConstraintRackRowsFkRoom = "rack_rows_fk_room"
	// ConstraintRackRowsUqRoomName is defined on core.rack_rows.
	ConstraintRackRowsUqRoomName = "rack_rows_uq_room_name"
	// ConstraintRacksFkRackRow is defined on core.racks.
	ConstraintRacksFkRackRow = "racks_fk_rack_row"
	// ConstraintRacksUqRackRowName is defined on core.racks.
	ConstraintRacksUqRackRowName = "racks_uq_rack_row_name"
	// ConstraintRoomsFkSite is defined on core.rooms.
	ConstraintRoomsFkSite = "rooms_fk_site"
	// ConstraintRoomsUqSiteName is defined on core.rooms.
	ConstraintRoomsUqSiteName = "rooms_uq_site_name"
	// ConstraintSitesUqName is defined on core.sites.
	ConstraintSitesUqName = "sites_uq_name"
)
