apiVersion: v1
kind: Namespace
metadata:
  name: tn-dcim-pr-${PR_NUM}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcim-pr-${PR_NUM}
  namespace: tn-dcim-pr-${PR_NUM}
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/dcim
      sourceRef:
        kind: GitRepository
        name: dcim
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    externalUrls:
      api: https://api.pr${PR_NUM}.${DOMAIN}
      console: https://console.pr${PR_NUM}.${DOMAIN}

    images:
      dbMigrations: ${IMAGE_PREFIX}/db-migrations:${IMAGE_TAG}
      api: ${IMAGE_PREFIX}/api:${IMAGE_TAG}
      frontend: ${IMAGE_PREFIX}/frontend:${IMAGE_TAG}

    db:
      enabled: true
      instances: 1
      storageSize: 1Gi
      reset: true
      insertTestData: true

    api:
      enabled: true
      replicas: 1
      logLevel: debug

    frontend:
      enabled: true
      replicas: 1

    ingress:
      enabled: true
      className: nginx
      domain: ${DOMAIN}
      subdomainInfix: "pr${PR_NUM}."
      tls:
        clusterIssuer: letsencrypt-prod
